### ISSUE TITLE
control.lua:191: attempt to compare nil with number

### ISSUE THREAD

**Issue by Chaoziken** [sproott/ResourceLabelsUpdated#1]
When trying to press Shift + G to show labels, this message gets returned every time it tries to label an ore, and it ends up not labeling the ore. Looking into it, it seems that "resource-labels-maximum-resource-count" was not added to the cacheSettings function, so trying to access that cached setting with global.settings returned nil.

The fix is simple: add `cacheSetting(settings, "resource-labels-maximum-resource-count")` to `cacheSettings()` in control.lua. I can try to create a pull request with this fix once I figure out how to.

**Comment by sproott** [comment]
The fix will appear in the next release.
